[greeter]
background=/usr/share/backgrounds/debianmoss/tiles.png
theme-name=DebianMOSS-Greeter
icon-theme-name=Papirus-Dark
font-name=Noto Sans 11
xft-antialias=true
xft-dpi=96
xft-hintstyle=hintslight
xft-rgba=rgb
user-background=false
hide-user-image=false
default-user-image=/usr/share/pixmaps/debianmoss-logo.png
clock-format=%A  %d %b  %H:%M
panel-position=bottom
active-monitor=#cursor
indicators=~session;~language;~spacer;~clock;~spacer;~power
